import { execFile } from "node:child_process";
import { existsSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

/**
 * Wires the admin-ui daemon into a shared host Caddy, if one is already set
 * up, so it's reachable at a fixed hostname (`indusk.dawn`) instead of a port
 * that can vary. indusk does not install or manage Caddy or DNS itself — this
 * module only participates when `~/.indusk/proxy/sites/` already exists (the
 * convention an already-running host Caddy imports from), and no-ops
 * gracefully everywhere else. Never throws.
 */

export const ADMIN_HOSTNAME = "indusk.dawn";
const SITE_FILENAME = "indusk-admin.caddyfile";
const DEFAULT_CADDY_CONFIG_PATH = "/opt/homebrew/etc/Caddyfile";

function induskHome(): string {
	return process.env.INDUSK_HOME ?? join(homedir(), ".indusk");
}

function proxySitesDir(): string {
	return join(induskHome(), "proxy", "sites");
}

function sitePath(): string {
	return join(proxySitesDir(), SITE_FILENAME);
}

function caddyConfigPath(): string {
	return process.env.INDUSK_CADDY_CONFIG_PATH ?? DEFAULT_CADDY_CONFIG_PATH;
}

function caddyfileBlock(port: number): string {
	return `# Generated by \`indusk ui\` — DO NOT EDIT
${ADMIN_HOSTNAME} {
	tls {
		issuer internal {
			lifetime 720h
			sign_with_root
		}
	}
	reverse_proxy 127.0.0.1:${port}
}
`;
}

export interface ProxyRouteResult {
	/** Whether the Caddyfile block was written or removed. */
	changed: boolean;
	/** Whether a running Caddy was told to pick up the change. */
	reloaded: boolean;
	/** Present when `changed`/`reloaded` don't both fully succeed — never an exception. */
	reason?: string;
}

/**
 * Write (or update) the `indusk.dawn` -> `127.0.0.1:<port>` block and reload
 * Caddy so the change is live immediately. No-ops when the shared proxy
 * sites directory doesn't exist on this machine.
 */
export async function registerAdminRoute(port: number): Promise<ProxyRouteResult> {
	if (!existsSync(proxySitesDir())) {
		return {
			changed: false,
			reloaded: false,
			reason: `no shared proxy sites directory at ${proxySitesDir()}`,
		};
	}

	writeFileSync(sitePath(), caddyfileBlock(port));
	const reload = await reloadCaddy();
	return { changed: true, ...reload };
}

/**
 * Remove the `indusk.dawn` route and reload Caddy, so a stopped daemon
 * doesn't leave behind a route that 502s. No-ops when no route is currently
 * registered.
 */
export async function deregisterAdminRoute(): Promise<ProxyRouteResult> {
	if (!existsSync(sitePath())) {
		return { changed: false, reloaded: false, reason: "no route was registered" };
	}

	rmSync(sitePath(), { force: true });
	const reload = await reloadCaddy();
	return { changed: true, ...reload };
}

async function reloadCaddy(): Promise<{ reloaded: boolean; reason?: string }> {
	const configPath = caddyConfigPath();
	if (!existsSync(configPath)) {
		return { reloaded: false, reason: `no Caddy config found at ${configPath} — reload manually` };
	}
	try {
		await execFileAsync("caddy", ["reload", "--config", configPath]);
		return { reloaded: true };
	} catch (err) {
		return {
			reloaded: false,
			reason: `\`caddy reload\` failed: ${err instanceof Error ? err.message : String(err)}`,
		};
	}
}
